import Link from "next/link";
import { Icon } from "@/components/icons";
import { listAccessibleBrands } from "@/modules/brands/queries";
import { listAccessibleContent, listAccessibleContentOwners } from "@/modules/content/queries";
import { parseContentSearch } from "@/modules/content/search";
import { contentStatusLabel, formatKoreanDate } from "@/modules/content/display";
import { getWorkspaceContext } from "@/modules/auth/workspace";
import { createContent } from "@/modules/content-studio/actions";

type Params = Promise<Record<string, string | string[] | undefined>>;
type NamedValue = { id: string; name?: string; display_name?: string } | { id: string; name?: string; display_name?: string }[] | null;
const one = (value: NamedValue) => Array.isArray(value) ? value[0] : value;

export default async function ContentPage({ searchParams }: { searchParams: Params }) {
  const raw = await searchParams;
  const context = await getWorkspaceContext();
  const search = parseContentSearch(raw);
  const [result, brands, owners] = await Promise.all([listAccessibleContent(search), listAccessibleBrands(), listAccessibleContentOwners()]);
  const hasFilters = Boolean(search.q || search.brandId || search.status || search.ownerId);
  const queryForPage = (page: number) => { const params = new URLSearchParams(); for (const [key, value] of Object.entries({ q: search.q, brandId: search.brandId, status: search.status, ownerId: search.ownerId, page: String(page) })) if (value) params.set(key, value); return `/workspace/content?${params}`; };
  return <main className="workspace-content"><section className="page-heading"><div><p className="eyebrow">CONTENT WORKFLOW</p><h1>콘텐츠 관리</h1><p>브랜드별 콘텐츠를 검색하고 작업 상태를 관리합니다.</p></div>{context.role !== "advertiser" && <details className="create-popover"><summary className="primary-button"><Icon name="plus" />새 콘텐츠</summary><form action={createContent} className="management-form content-create-form"><div className="popover-heading"><strong>새 콘텐츠 만들기</strong><span>기본 정보를 입력하면 블록 스튜디오가 열립니다.</span></div><label>브랜드<select name="brandId" required><option value="">브랜드 선택</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><label>콘텐츠 제목<input name="title" required maxLength={160} placeholder="가상 탐험 도구 선택 가이드" /></label><label>URL 슬러그<input name="slug" required placeholder="virtual-explorer-guide" /></label><label>핵심 키워드<input name="primaryKeyword" maxLength={120} placeholder="가상 탐험 도구" /></label><button className="primary-button">콘텐츠 생성</button></form></details>}</section>
    <form className="filter-panel"><div className="filter-grid"><label className="search-field"><span>제목 또는 키워드</span><span className="input-with-icon"><Icon name="search" /><input name="q" defaultValue={search.q} placeholder="콘텐츠 검색" /></span></label><label><span>브랜드</span><select name="brandId" defaultValue={search.brandId ?? ""}><option value="">전체 브랜드</option>{brands.map((brand) => <option value={brand.id} key={brand.id}>{brand.name}</option>)}</select></label><label><span>상태</span><select name="status" defaultValue={search.status ?? ""}><option value="">전체 상태</option>{Object.entries(contentStatusLabel).filter(([value]) => value !== "scheduled" && value !== "archived").map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>담당자</span><select name="ownerId" defaultValue={search.ownerId ?? ""}><option value="">전체 담당자</option>{owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.name}</option>)}</select></label><button className="primary-button filter-submit">필터 적용</button></div>{hasFilters && <div className="active-filters"><span>적용된 필터</span>{search.q && <em>검색: {search.q}</em>}{search.brandId && <em>{brands.find((brand) => brand.id === search.brandId)?.name}</em>}{search.status && <em>{contentStatusLabel[search.status]}</em>}{search.ownerId && <em>{owners.find((owner) => owner.id === search.ownerId)?.name}</em>}<Link href="/workspace/content">필터 초기화</Link></div>}</form>
    <section className="panel content-panel"><div className="panel-title"><div><h2>{hasFilters ? "검색 결과" : "전체 콘텐츠"}</h2><span>{result.total}개 콘텐츠</span></div><span>최근 수정일 순</span></div>{result.items.length === 0 ? <div className="state-card flat"><span className="state-icon"><Icon name={hasFilters ? "search" : "content"} /></span><h3>{hasFilters ? "조건에 맞는 콘텐츠가 없습니다" : "아직 콘텐츠가 없습니다"}</h3><p>{hasFilters ? "검색어나 필터를 변경하거나 초기화해 보세요." : "새 콘텐츠를 만들어 작업을 시작해 보세요."}</p>{hasFilters && <Link className="secondary-button" href="/workspace/content">필터 초기화</Link>}</div> : <div className="content-table" role="table" aria-label="콘텐츠 목록"><div className="content-table-head" role="row"><span role="columnheader">브랜드</span><span role="columnheader">콘텐츠 제목</span><span role="columnheader">핵심 키워드 / 슬러그</span><span role="columnheader">상태</span><span role="columnheader">담당자</span><span role="columnheader">최근 수정일</span><span role="columnheader">작업</span></div>{result.items.map((item) => { const brand = one(item.brands as NamedValue); const owner = one(item.profiles as NamedValue); const version = one(item.content_versions as NamedValue & { version_no?: number }); const href = `/workspace/content/${item.id}/studio`; return <article role="row" key={item.id}><span role="cell"><span className="brand-tag">{brand?.name ?? "가상 브랜드"}</span></span><span role="cell" className="content-title-cell"><Link href={href}>{item.title}</Link><small>{version && "version_no" in version ? `명시적 버전 v${version.version_no}` : "아직 명시적 버전이 없습니다"}</small></span><span role="cell"><strong>{item.primary_keyword || "핵심 키워드 미입력"}</strong><small>{item.slug}</small></span><span role="cell"><span className={`status-badge status-${item.status}`}>{contentStatusLabel[item.status] ?? item.status}</span></span><span role="cell" className="owner-cell">{owner?.display_name ?? "담당자 미지정"}</span><span role="cell"><time dateTime={item.updated_at}>{formatKoreanDate(item.updated_at)}</time></span><span role="cell"><Link className="row-action" href={href}>{context.role === "advertiser" ? "읽기" : "열기"}<Icon name="arrow" /></Link></span></article>; })}</div>}
      <nav className="pagination" aria-label="페이지 이동"><Link aria-disabled={result.page <= 1} href={queryForPage(Math.max(1, result.page - 1))}>이전</Link><span><strong>{result.page}</strong> / {result.pageCount}</span><Link aria-disabled={result.page >= result.pageCount} href={queryForPage(Math.min(result.pageCount, result.page + 1))}>다음</Link></nav></section>
  </main>;
}
