import { createHash } from "node:crypto";
export type ExtractedFact={type:string;key:string;value:unknown;location:Record<string,unknown>;riskLevel:"low"|"price"|"efficacy"|"performance"|"numeric"};
export type ExtractedProduct={productKey:string;name:string;officialUrl:string;description:string|null;price:number|null;currency:string|null;inventoryStatus:string|null;rating:number|null;reviewCount:number|null;imageUrl:string|null;imageAlt:string|null};
export type ExtractedPage={title:string|null;description:string|null;canonical:string|null;openGraph:Record<string,string>;jsonLd:unknown[];visibleText:string;links:Array<{url:string;text:string}>;images:Array<{url:string;alt:string}>;pageType:"home"|"about"|"category"|"product"|"faq"|"other";classificationSignals:string[];facts:ExtractedFact[];products:ExtractedProduct[];contentHash:string};
const entities:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "};
function decode(value:string){return value.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi,(_,token:string)=>{if(token.startsWith("#x"))return String.fromCodePoint(parseInt(token.slice(2),16));if(token.startsWith("#"))return String.fromCodePoint(parseInt(token.slice(1),10));return entities[token.toLowerCase()]??" ";});}
function cleanText(value:string,max:number){return decode(value.replace(/<[^>]*>/g," ")).replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,"[redacted]").replace(/(?:\+?82[- ]?)?0\d{1,2}[- ]?\d{3,4}[- ]?\d{4}/g,"[redacted]").replace(/\s+/g," ").trim().slice(0,max);}
function attr(tag:string,name:string){const match=tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`,`i`));return match?decode(match[1].trim()):null;}
function absolute(raw:string|null,base:string){if(!raw)return null;try{const url=new URL(raw,base);return ["http:","https:"].includes(url.protocol)?url.toString():null;}catch{return null;}}
function meta(html:string,key:string,attribute="name"){const pattern=new RegExp(`<meta\\b[^>]*${attribute}\\s*=\\s*["']${key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}["'][^>]*>`,`i`);const tag=html.match(pattern)?.[0];return tag?attr(tag,"content"):null;}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value);}
function flattenLd(value:unknown):Record<string,unknown>[] {if(Array.isArray(value))return value.flatMap(flattenLd);if(!value||typeof value!=="object")return[];const object=value as Record<string,unknown>;return [object,...flattenLd(object["@graph"])];}
function types(item:Record<string,unknown>){return(Array.isArray(item["@type"])?item["@type"]:[item["@type"]]).filter((v):v is string=>typeof v==="string");}
function numberValue(value:unknown){const number=typeof value==="number"?value:Number(value);return Number.isFinite(number)?number:null;}
export function extractPage(html:string,pageUrl:string):ExtractedPage{
  const jsonLd:unknown[]=[];for(const match of html.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){if(jsonLd.length>=20)break;try{const raw=match[1].trim();if(raw.length<=262144)jsonLd.push(JSON.parse(raw));}catch{}}
  const title=cleanText(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]??"",500)||null;const description=meta(html,"description")?.slice(0,2000)??null;
  const canonicalTag=html.match(/<link\b[^>]*rel\s*=\s*["'][^"']*canonical[^"']*["'][^>]*>/i)?.[0]??"";const canonical=absolute(attr(canonicalTag,"href"),pageUrl);
  const openGraph:Record<string,string>={};for(const match of html.matchAll(/<meta\b[^>]*(?:property|name)\s*=\s*["'](og:[^"']+)["'][^>]*>/gi)){const content=attr(match[0],"content");if(content&&Object.keys(openGraph).length<20)openGraph[match[1]]=content.slice(0,2000);}
  const sanitized=html.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<noscript\b[\s\S]*?<\/noscript>/gi," ").replace(/<(svg|iframe|object|embed)\b[\s\S]*?<\/\1>/gi," ");
  const visibleText=cleanText(sanitized,524288);const links=[...sanitized.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].slice(0,500).flatMap((match)=>{const url=absolute(match[1],pageUrl);return url?[{url,text:cleanText(match[2],300)}]:[]});
  const images=[...sanitized.matchAll(/<img\b[^>]*>/gi)].slice(0,200).flatMap((match)=>{const url=absolute(attr(match[0],"src"),pageUrl);return url?[{url,alt:cleanText(attr(match[0],"alt")??"",500)}]:[]});
  const nodes=jsonLd.flatMap(flattenLd),signals:string[]=[];if(nodes.some((item)=>types(item).includes("Product")))signals.push("jsonld:Product");if(nodes.some((item)=>types(item).includes("FAQPage")))signals.push("jsonld:FAQPage");if(nodes.some((item)=>types(item).includes("Organization")))signals.push("jsonld:Organization");if(nodes.some((item)=>types(item).includes("BreadcrumbList")))signals.push("jsonld:BreadcrumbList");
  const path=new URL(pageUrl).pathname.toLowerCase();let pageType:ExtractedPage["pageType"]="other";if(signals.includes("jsonld:Product"))pageType="product";else if(signals.includes("jsonld:FAQPage"))pageType="faq";else if(/\/(category|categories|collections?)(\/|$)/.test(path))pageType="category";else if(signals.includes("jsonld:Organization")||/\/(about|brand)(\/|$)/.test(path))pageType="about";else if(path==="/"||path==="")pageType="home";
  const facts:ExtractedFact[]=[];const products:ExtractedProduct[]=[];for(const item of nodes){const itemTypes=types(item);if(itemTypes.includes("Organization")){if(typeof item.name==="string")facts.push({type:"organization",key:"name",value:item.name,location:{kind:"json-ld",path:"Organization.name"},riskLevel:"low"});if(typeof item.url==="string")facts.push({type:"organization",key:"official_url",value:item.url,location:{kind:"json-ld",path:"Organization.url"},riskLevel:"low"});if(typeof item.description==="string")facts.push({type:"organization",key:"description",value:item.description,location:{kind:"json-ld",path:"Organization.description"},riskLevel:"low"});}
    if(itemTypes.includes("FAQPage")&&Array.isArray(item.mainEntity))for(const [index,entry] of item.mainEntity.entries()){if(!entry||typeof entry!=="object")continue;const question=entry as Record<string,unknown>,answer=question.acceptedAnswer as Record<string,unknown>|undefined;if(typeof question.name==="string"&&typeof answer?.text==="string")facts.push({type:"faq",key:`question_${index+1}`,value:{question:question.name,answer:answer.text},location:{kind:"json-ld",path:`FAQPage.mainEntity[${index}]`},riskLevel:"low"});}
    if(itemTypes.includes("Product")){const offers=(Array.isArray(item.offers)?item.offers[0]:item.offers) as Record<string,unknown>|undefined;const rating=item.aggregateRating as Record<string,unknown>|undefined;const image=Array.isArray(item.image)?item.image[0]:item.image;const name=typeof item.name==="string"?item.name:"";if(!name)continue;const official=absolute(typeof offers?.url==="string"?offers.url:pageUrl,pageUrl)??pageUrl;const product={productKey:new URL(official).pathname.split("/").filter(Boolean).at(-1)??createHash("sha256").update(name).digest("hex").slice(0,16),name,officialUrl:official,description:typeof item.description==="string"?item.description.slice(0,20000):null,price:numberValue(offers?.price),currency:typeof offers?.priceCurrency==="string"?offers.priceCurrency:null,inventoryStatus:typeof offers?.availability==="string"?offers.availability:null,rating:numberValue(rating?.ratingValue),reviewCount:numberValue(rating?.reviewCount),imageUrl:absolute(typeof image==="string"?image:null,pageUrl),imageAlt:images.find((candidate)=>candidate.url===absolute(typeof image==="string"?image:null,pageUrl))?.alt??null};products.push(product);facts.push({type:"product",key:`${product.productKey}.name`,value:name,location:{kind:"json-ld",path:"Product.name"},riskLevel:"low"});if(product.price!==null)facts.push({type:"product",key:`${product.productKey}.price`,value:{price:product.price,currency:product.currency},location:{kind:"json-ld",path:"Product.offers.price"},riskLevel:"price"});if(product.rating!==null)facts.push({type:"product",key:`${product.productKey}.rating`,value:{rating:product.rating,reviewCount:product.reviewCount},location:{kind:"json-ld",path:"Product.aggregateRating"},riskLevel:"numeric"});}}
  const hashInput={title,description,canonical,openGraph,jsonLd,visibleText,links,images};return{title,description,canonical,openGraph,jsonLd,visibleText,links,images,pageType,classificationSignals:signals,facts,products,contentHash:createHash("sha256").update(stable(hashInput)).digest("hex")};
}
