// @vitest-environment node
import { afterEach,describe,expect,it } from "vitest";import http from "node:http";import { once } from "node:events";
import { assertTargetUrl,isForbiddenAddress,isLocalTestExceptionAllowed } from "./security";import { secureCrawlRequest } from "./transport";import { parseRobots,parseSitemap } from "./discovery";
const servers:http.Server[]=[];afterEach(async()=>{await Promise.all(servers.splice(0).map((server)=>new Promise<void>((resolve)=>server.close(()=>resolve()))));});
async function localServer(handler:http.RequestListener){const server=http.createServer(handler);servers.push(server);server.listen(0,"127.0.0.1");await once(server,"listening");const address=server.address();if(!address||typeof address==="string")throw new Error("server");return`http://127.0.0.1:${address.port}`;}
describe("crawler security",()=>{
it("blocks private, metadata, mapped IPv4 and reserved IPv6",()=>{for(const ip of ["127.0.0.1","10.0.0.1","169.254.169.254","100.100.100.200","::1","::ffff:127.0.0.1","fd00::1","fe80::1"])expect(isForbiddenAddress(ip)).toBe(true);});
it("blocks unsafe protocols, credentials, sensitive paths and query grids",()=>{const policy={allowedDomains:["example.com"],allowLocalTest:false};for(const url of ["file:///tmp/a","https://u:p@example.com/","https://example.com/checkout","https://example.com/calendar/2026/08","https://example.com/products?q=x"])expect(()=>assertTargetUrl(url,policy)).toThrow();});
it("requires the exact local exception contract",()=>{expect(isLocalTestExceptionAllowed({platformType:"local-test-store",baseUrl:"http://127.0.0.1:3100"},{NODE_ENV:"test",CRAWLER_LOCAL_TEST_ENABLED:"true"} as NodeJS.ProcessEnv)).toBe(true);expect(isLocalTestExceptionAllowed({platformType:"custom",baseUrl:"http://127.0.0.1:3100"},{NODE_ENV:"test",CRAWLER_LOCAL_TEST_ENABLED:"true"} as NodeJS.ProcessEnv)).toBe(false);});
it("pins the local connection and enforces response size",async()=>{const origin=await localServer((_req,res)=>{res.setHeader("Content-Type","text/html");res.end("x".repeat(200));});const options={allowedDomains:[],allowLocalTest:true,expectedLocalOrigin:origin,resolver:async()=>[{address:"127.0.0.1",family:4}]};await expect(secureCrawlRequest(origin,options)).resolves.toMatchObject({status:200,remoteAddress:"127.0.0.1"});await expect(secureCrawlRequest(origin,{...options,maxBytes:20})).rejects.toMatchObject({code:"CRAWLER_RESPONSE_TOO_LARGE"});});
it("revalidates redirect destinations",async()=>{const origin=await localServer((_req,res)=>{res.statusCode=302;res.setHeader("Location","http://169.254.169.254/latest/meta-data");res.end();});await expect(secureCrawlRequest(origin,{allowedDomains:[],allowLocalTest:true,expectedLocalOrigin:origin,resolver:async(host)=>[{address:host,family:4}]})).rejects.toMatchObject({code:"CRAWLER_DOMAIN_NOT_ALLOWED"});});
it("times out slow responses",async()=>{const origin=await localServer((_req,res)=>setTimeout(()=>{res.setHeader("Content-Type","text/html");res.end("late");},100));await expect(secureCrawlRequest(origin,{allowedDomains:[],allowLocalTest:true,expectedLocalOrigin:origin,timeoutMs:10,resolver:async()=>[{address:"127.0.0.1",family:4}]})).rejects.toMatchObject({code:"CRAWLER_TIMEOUT"});});
it("parses bounded robots and sitemap data",()=>{expect(parseRobots("User-agent: *\nDisallow: /checkout\nSitemap: http://127.0.0.1:3100/sitemap.xml")).toEqual({disallow:["/checkout"],sitemaps:["http://127.0.0.1:3100/sitemap.xml"]});expect(parseSitemap("<urlset><url><loc>https://example.com/a&amp;b</loc></url></urlset>")).toEqual(["https://example.com/a&b"]);});
});
