import { isIP } from "node:net";

export class CrawlSecurityError extends Error { constructor(readonly code:string,message:string){super(message);this.name="CrawlSecurityError";} }
export type CrawlSecurityPolicy={allowedDomains:readonly string[];allowLocalTest:boolean;expectedLocalOrigin?:string};
const blockedPath=/(^|\/)(login|logout|member|members|account|mypage|my-page|order|orders|checkout|payment|payments|cart|basket|shipping|tracking|search|calendar)(\/|$)/i;
const calendarPath=/(^|\/)(19|20)\d{2}([/-](0?[1-9]|1[0-2])){1,2}(\/|$)/;

function ipv4Number(ip:string){const parts=ip.split(".").map(Number);if(parts.length!==4||parts.some((v)=>!Number.isInteger(v)||v<0||v>255))return null;return (((parts[0]<<24)>>>0)+(parts[1]<<16)+(parts[2]<<8)+parts[3])>>>0;}
function inV4(ip:string,base:string,bits:number){const value=ipv4Number(ip),start=ipv4Number(base);if(value===null||start===null)return false;const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;return (value&mask)===(start&mask);}
export function normalizeIp(ip:string){const clean=ip.toLowerCase().split("%")[0];return clean.startsWith("::ffff:")&&isIP(clean.slice(7))===4?clean.slice(7):clean;}
export function isForbiddenAddress(raw:string){const ip=normalizeIp(raw);const family=isIP(ip);if(family===4)return [["0.0.0.0",8],["10.0.0.0",8],["100.64.0.0",10],["127.0.0.0",8],["169.254.0.0",16],["172.16.0.0",12],["192.0.0.0",24],["192.0.2.0",24],["192.168.0.0",16],["198.18.0.0",15],["198.51.100.0",24],["203.0.113.0",24],["224.0.0.0",4],["240.0.0.0",4]].some(([base,bits])=>inV4(ip,String(base),Number(bits)));if(family===6)return ip==="::"||ip==="::1"||/^(f[cd]|fe[89ab]|ff)/.test(ip)||ip.startsWith("2001:db8:");return true;}
export function assertAllowedAddress(ip:string,allowLocalTest:boolean){if(!isForbiddenAddress(ip))return;if(allowLocalTest&&normalizeIp(ip)==="127.0.0.1")return;throw new CrawlSecurityError("CRAWLER_FORBIDDEN_ADDRESS","수집이 허용되지 않은 네트워크 주소입니다.");}
export function assertTargetUrl(raw:string,policy:CrawlSecurityPolicy){let url:URL;try{url=new URL(raw);}catch{throw new CrawlSecurityError("CRAWLER_INVALID_URL","올바른 HTTP URL이 아닙니다.");}if(!["http:","https:"].includes(url.protocol))throw new CrawlSecurityError("CRAWLER_FORBIDDEN_PROTOCOL","HTTP와 HTTPS만 허용됩니다.");if(url.username||url.password)throw new CrawlSecurityError("CRAWLER_URL_CREDENTIALS","인증정보가 포함된 URL은 허용되지 않습니다.");url.hash="";const host=url.hostname.toLowerCase().replace(/\.$/,"");const allowed=policy.allowedDomains.some((item)=>host===item||host.endsWith(`.${item}`));const localAllowed=policy.allowLocalTest&&policy.expectedLocalOrigin&&url.origin===policy.expectedLocalOrigin&&host==="127.0.0.1";if(!allowed&&!localAllowed)throw new CrawlSecurityError("CRAWLER_DOMAIN_NOT_ALLOWED","등록된 허용 도메인만 수집할 수 있습니다.");let decoded=url.pathname;try{decoded=decodeURIComponent(decoded);}catch{}if(blockedPath.test(decoded)||calendarPath.test(decoded))throw new CrawlSecurityError("CRAWLER_PATH_BLOCKED","민감하거나 무한 탐색 위험이 있는 경로는 수집하지 않습니다.");if([...url.searchParams.keys()].length>8||[...url.searchParams.keys()].some((key)=>/^(q|query|search|keyword|date|day|month|year|calendar)$/i.test(key)))throw new CrawlSecurityError("CRAWLER_QUERY_BLOCKED","검색·캘린더형 쿼리는 수집하지 않습니다.");return url;}
export function isLocalTestExceptionAllowed(source:{platformType:string;baseUrl:string},env:NodeJS.ProcessEnv=process.env){return source.platformType==="local-test-store"&&env.CRAWLER_LOCAL_TEST_ENABLED==="true"&&["development","test"].includes(env.NODE_ENV??"")&&new URL(source.baseUrl).origin==="http://127.0.0.1:3100";}
