import Link from "next/link";
import { ProductReviewForm } from "@/components/site-knowledge-actions";
import { getBrand } from "@/modules/brands/queries";
import { formatKoreanDate } from "@/modules/content/display";
import { getSiteKnowledge } from "@/modules/site-crawl/queries";

export default async function ProductsPage({ params }: { params: Promise<{ brandId: string }> }) {
  const { brandId } = await params; const [brand, data] = await Promise.all([getBrand(brandId), getSiteKnowledge(brandId)]);
  return <main className="workspace-content"><Link className="back-link" href={`/workspace/brands/${brandId}`}>← 브랜드 상세</Link><section className="page-heading"><div><p className="eyebrow">PRODUCT REVIEW</p><h1>{brand.name} 상품 정보</h1><p>가격·재고·설명 변경은 필드별로 검수하며, 미승인 동적 값은 생성 입력에서 제외합니다.</p></div><nav className="section-nav" aria-label="사이트 지식 메뉴"><Link href={`/workspace/brands/${brandId}/site-crawl`}>사이트 수집</Link><Link href={`/workspace/brands/${brandId}/knowledge`}>브랜드 지식</Link><Link aria-current="page" href={`/workspace/brands/${brandId}/products`}>상품 정보</Link></nav></section>
    <section className="panel"><div className="panel-title"><div><h2>상품 후보</h2><span>{data.products.length}개 스냅샷</span></div></div><div className="product-review-grid">{data.products.length === 0 ? <p className="empty-copy">수집된 상품 후보가 없습니다.</p> : data.products.map((product) => <article className="knowledge-card" key={product.id}><header><div><span className={`status-badge status-${product.status === "approved" ? "active" : product.status === "rejected" ? "archived" : "warning"}`}><span />{product.status === "approved" ? "승인" : product.status === "rejected" ? "반려" : "검수 필요"}</span><h3>{product.name}</h3></div></header><dl><div><dt>가격</dt><dd>{product.price == null ? "제공 없음" : `${Number(product.price).toLocaleString("ko-KR")} ${product.currency ?? ""}`}</dd></div><div><dt>재고</dt><dd>{product.inventory_status ?? "제공 없음"}</dd></div><div><dt>설명</dt><dd>{product.description ?? "제공 없음"}</dd></div></dl><a href={product.official_url} target="_blank" rel="noreferrer">공식 상품 페이지</a><p className="field-review-summary">필드 상태: {Object.entries(product.field_review_status as Record<string,string>).map(([key,value]) => `${key} ${value === "approved" ? "승인" : "검수 대기"}`).join(" · ")}</p><small>{product.agency_reviewed_at ? `대행사 검수 완료 · ${formatKoreanDate(product.agency_reviewed_at)}` : "대행사 검수 전"} / {product.advertiser_reviewed_at ? `광고주 확인 완료 · ${formatKoreanDate(product.advertiser_reviewed_at)}` : "광고주 확인 전"}</small><ProductReviewForm brandId={brandId} itemId={product.id} /></article>)}</div></section></main>;
}
